services:
  api-dev:
    hostname: "api-dev"
    image: api-dev
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    environment:
      - DJANGO_LOGGING_FORMATTER=${LOGGING_FORMATTER:-human_readable}
      - UV_NO_SYNC=1
      - UV_FROZEN=1
    env_file:
      - path: .env
        required: false
    ports:
      - "${DJANGO_PORT:-8080}:${DJANGO_PORT:-8080}"
    volumes:
      - ./backend:/app
      - /app/.venv
      - ./_data/api:/app/.config/api
    depends_on:
      postgres:
        condition: service_healthy
    command: ["dev"]

  ui-dev:
    hostname: "ui-dev"
    image: ui-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    user: "node"
    env_file:
      - path: .env
        required: false
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/apps/web/.next
    depends_on:
      - api-dev

  postgres:
    image: postgres:16.3-alpine3.20
    hostname: "postgres-db"
    volumes:
      - ./_data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    env_file:
      - path: .env
        required: false
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  frontend_node_modules:
